### ISSUE TITLE
Release 2 Summary

### ISSUE THREAD

**Issue by heyhellomila** [milaroisin/SOEN390-VigilantCamera#31]
As a client, I want to be able to track the progress of the project.

* [x] Write a summary of the second release for the client.
* [x] Mockups for Release 3 features: geotagging #38 
* [x] Update Product Backlog for Release 2. #45 
* [x] Revamp Issues with Story Points with references for Tracebility.
* [x] Architecture Diagram updated #52 
* [x] Team Velocities Calculated

[Story Points: 8]
[Risk: Low]
[Priority: High]
