### ISSUE TITLE
Sprint 6: Testing

### ISSUE THREAD

**Issue by heyhellomila** [milaroisin/SOEN390-VigilantCamera#44]
As a developer, I would like to perform tests to ensure that my feature is working correctly.

* [x] Integrate Espresso in the gradle project.
* [x] Design acceptance tests for geotagging feature. #66 
* [x] Create UI tests filter feature.
* [x] Create UI tests for voice activation feature.
* [x] Create UI tests for geotagging feature.   
* [x] Create UI tests for QR scanner feature.
* [x] Integrate Jacoco as test coverage tool and reports.
* [x] Create unit tests for geotagging feature.
* [x] Create unit tests for QR feature.
* [x] Finish unit tests for filters.
* [x] Set up Firebase APM #63 
* [x] Configure Analytics and Performance tests for features. #63 
* [x] Write test scripts for CircleCI #60
* [x] Design acceptance tests for QR Scanner extra feature. #69 

[Story Points: 18]
[Risk: Medium]
[Priority: High]
